#Dockerfile 
# Base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy only package.json and package-lock.json first
COPY package*.json ./

# Install dependencies
RUN npm install

# Now copy the rest of the application files
COPY . .

# Expose the port
# EXPOSE 3000
EXPOSE 5173

# Run the application
CMD ["npm", "run", "dev"]
